spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/shelfaware}
spring.datasource.username=${DATABASE_USERNAME:shelfaware}
spring.datasource.password=${DATABASE_PASSWORD:shelfaware}
spring.datasource.driverClassName=org.postgresql.Driver
spring.h2.console.enabled=false
