ALTER TABLE shelf_items ADD COLUMN current_page INTEGER NOT NULL DEFAULT 0;
ALTER TABLE shelf_items ADD COLUMN favorite BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE shelf_items
SET favorite = TRUE,
    status = 'FINISHED',
    finished_on = COALESCE(finished_on, CAST(updated_at AS DATE))
WHERE status = 'FAVORITE';

ALTER TABLE shelf_items ADD CONSTRAINT chk_shelf_current_page CHECK (current_page >= 0);

CREATE TABLE reading_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shelf_item_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    read_on DATE NOT NULL,
    start_page INTEGER NOT NULL,
    end_page INTEGER NOT NULL,
    pages_read INTEGER NOT NULL,
    completed_book BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_reading_sessions_shelf FOREIGN KEY (shelf_item_id) REFERENCES shelf_items(id) ON DELETE CASCADE,
    CONSTRAINT fk_reading_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_reading_session_pages CHECK (start_page >= 0 AND end_page > start_page AND pages_read = end_page - start_page)
);

CREATE TABLE reading_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    goal_year INTEGER NOT NULL,
    target_books INTEGER,
    target_pages INTEGER,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_reading_goals_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_reading_goals_user_year UNIQUE (user_id, goal_year),
    CONSTRAINT chk_reading_goal_year CHECK (goal_year BETWEEN 2000 AND 2100),
    CONSTRAINT chk_reading_goal_targets CHECK (
        (target_books IS NOT NULL AND target_books > 0) OR
        (target_pages IS NOT NULL AND target_pages > 0)
    )
);

CREATE INDEX idx_reading_sessions_user_date ON reading_sessions(user_id, read_on);
CREATE INDEX idx_reading_sessions_shelf_created ON reading_sessions(shelf_item_id, created_at);
